version: '3.7'
services:
    database:
        container_name: database-market
        image: postgres:12
        volumes:
            - ${HOME}/Docker/postgres/market:/var/lib/postgresql/data
            - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/db.changelog-schema.sql
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${MARKET_DATABASE_USER}
            POSTGRES_PASSWORD: ${MARKET_DATABASE_PASSWORD}
            POSTGRES_DB: ${MARKET_DATABASE_NAME}
        ports:
            - "5432:5432"
        networks:
            - market

    street-market:
        hostname: street-market
        container_name: street-market
        image: street-market:latest
        command: sh -c './wait-for database:5432 -- echo "Database is ready"'
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            MARKET_DATABASE_USER: ${MARKET_DATABASE_USER}
            MARKET_DATABASE_PASSWORD: ${MARKET_DATABASE_PASSWORD}
            MARKET_DATABASE_NAME: ${MARKET_DATABASE_NAME}
            MARKET_DATABASE_HOST: ${MARKET_DATABASE_HOST}
            MARKET_DATABASE_PORT: ${MARKET_DATABASE_PORT}
        depends_on:
            - database
        ports:
            - "8080:8080"
        networks:
            - market

networks:
    market:
        driver: bridge
