CREATE SCHEMA IF NOT EXISTS MARKET;

CREATE TABLE IF NOT EXISTS MARKET.CENSUS
(
    SECTOR         BIGINT       NOT NULL,
    WEIGHTING_AREA BIGINT       NOT NULL,
    DISTRICT_CODE  INTEGER      NOT NULL,
    DISTRICT       VARCHAR(250) NOT NULL,
    BOROUGH_CODE   INTEGER      NOT NULL,
    BOROUGH        VARCHAR(250) NOT NULL,
    REGION5        VARCHAR(20)  NOT NULL,
    REGION8        VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_CENSUS PRIMARY KEY (SECTOR)
);

CREATE TABLE IF NOT EXISTS MARKET.STREET_MARKET
(
    UUID         UUID           NOT NULL,
    REGISTER     VARCHAR(10)    NOT NULL,
    NAME         VARCHAR(250)   NOT NULL,
    STREET       VARCHAR(250)   NOT NULL,
    NUMBER       VARCHAR(10) DEFAULT 'S/N',
    NEIGHBORHOOD VARCHAR(250)   NOT NULL,
    LANDMARK     VARCHAR(50),
    LAT          DECIMAL(10, 2) NOT NULL,
    LONG         DECIMAL(10, 2) NOT NULL,
    SECTOR_ID    BIGINT         NOT NULL,
    CONSTRAINT PK_STREET_MARKET PRIMARY KEY (UUID),
    CONSTRAINT FK_CENSUS FOREIGN KEY (SECTOR_ID) REFERENCES MARKET.CENSUS (SECTOR) ON DELETE CASCADE
);

ALTER TABLE MARKET.STREET_MARKET
    ADD CONSTRAINT UK_REGISTER UNIQUE (REGISTER);
